version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    env_file:
      - .env
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    restart: unless-stopped
